### ISSUE TITLE
train tokenizer code

### ISSUE THREAD

**Issue by Maniyantingliu** [LeonidasY/fast-vocabulary-transfer#2]
Hello, could you please share the code for training the tokenizer？

**Comment by LeonidasY** [comment]
Hi, we use the train_new_from_iterator method of the HuggingFace tokenizer for training. See the train_tokenizer function [here](https://github.com/LeonidasY/fast-vocabulary-transfer/blob/emnlp2022/utils/tokenization.py) for an example.
