### ISSUE TITLE
How do you determine which tokens to remove when reducing the vocabulary size in FVT?

### ISSUE THREAD

**Issue by PenutChen** [LeonidasY/fast-vocabulary-transfer#3]
Very interesting idea! I have some questions to ask. In the paper on FVT, you describe:

> We then define four vocabulary sizes for retraining our tokenizers. Specifically, we take the original vocabulary size and define it as a vocabulary size of 100%. We subsequently reduce this size to 75%, 50%, and 25%. From now on, we will refer to such tokenizers as $T_{100},T_{75},T_{50},T_{25}$ respectively, while the original vocabulary will be called $T_{gen}$.

At first glance, I'm not quite sure what the difference is between $T_{gen}$ and $T_{100}$. From the experiment results, it seems they are definitely two different vocabularies. Let's assume $T_{gen}$ has a vocabulary size of 1,000. I suppose you fix the in-domain vocabulary size (e.g., 250). So, do you remove 250 tokens from $T_{gen}$ and combine it with the in-domain vocabulary to get $T_{100}$? Similarly, for $T_{75}$, do you remove 500 tokens from $T_{gen}$ and add 250 in-domain tokens?

If my assumption is correct, then how do you decide which tokens to remove?

**Comment by LeonidasY** [comment]
Hi, T_gen is the baseline tokenizer, which in the paper is bert-base-cased. The vocabulary size of bert-base-cased is approximately 30000 tokens. On the other hand, T_100, T_75, T_50, and T_25 are the in-domain tokenizers. These are new tokenizers, whose vocabularies were constructed using the training set (in-domain data) via BPE. 

When creating a new tokenizer, one needs to specify the vocabulary size. In this case, the subscript is the percentage of the T_gen's vocabulary size to use. For example, the vocabulary size of T_50 is (50/100 * 30000) = 15000.

**Comment by PenutChen** [comment]
Got it, @LeonidasY! So T_100 is completely new vocabulary from T_gen, and you just determine the in-domain vocabulary size based on the original vocabulary size?

After your explanation, I find FVT to be more practical than I thought. Unlike recent approaches that only expand the vocabulary size and introduce a significant increase in model size just for decoding speed, FVT can also increase decoding speed and decrease model size. Amazing work!

I think applying this method to a decoder-only model may still face some challenges. I will try to address them based on your work. Thank you!

**Comment by LeonidasY** [comment]
Yes, both T_gen and T_100 are two distinct vocabularies, but of the same size in this case. The role of FVT is to initialize an embedding matrix for the new vocabulary by reusing information from a different vocabulary (and embedding matrix).

If you're interested, there is a recent work by the University of Edinburgh and Meta that validated FVT for larger generative models. Please see: https://arxiv.org/abs/2402.01035

**Comment by PenutChen** [comment]
Thank you for the recommendation! I found the code for the paper [here](https://github.com/gautierdag/tokenizer-bench) and share it for others who may need it.
